// Create Action
const initialState = {
  mgs: [],
  receiveMsg: [],
  curSeatID: 0,
  modalShow: false,
  updateChat:[],
  updateStatus:[],
  criticalError:[],
  notify:[],
  popupBuyin:[],
  seatPlayer:[],
  emptySeat:[],
  playerDealer:[],
  playerAction:[],
  playerTurn:[],
  showCard:{},
  highlightCards:[],
  playerWinner:[],
  playerActionStatus:[],
  playerBetStatus:[],
  mainPotStatus:[],
  updateBlinds:[],
  buyinSuccessful:[],
  tableDetails:[],
  connectionEstablished:[],
  reserveSeat:[],
  clearTable:[],
  reEstablishPos:[],
  showActions:[],
  resetClient:[],
  playerSitout:[],
  playerBackin:[],
  pause:[],
  updateStream:[],
  rebuyChips:[],
  gameFinished:[],
  redrawTable:[],
  mySeat:[],
  sitOutPlayer:[],
  disconnectionTimer:[],
  cancelBuyin:[],
  popupRebuy:[],
  allStatus: []
};

export default initialState;
