// Create Action
const initialState = {
  mgs: [],
  receiveMsg: [],
  curSeatID: 0,
  modalShow: false,
  isSittingOut: false,
  updateChat:[],
  updateStatus:[],
  criticalError:[],
  notify:[],
  popupBuyin: null,
  seatPlayer:{},
  emptySeat:[],
  playerDealer:[],
  playerAction:[],
  playerTurn: null,
  showCard:{},
  highlightCards:[],
  playerWinner:[],
  playerActionStatus:[],
  playerBetStatus:[],
  mainPotStatus: null,
  updateBlinds:[],
  buyinSuccessful:[],
  tableDetails: null,
  connectionEstablished:[],
  reserveSeat:[],
  clearTable:[],
  reEstablishPos:[],
  showActions:false,
  resetClient:[],
  playerSitout:[],
  playerBackin:[],
  pause:[],
  updateStream:[],
  rebuyChips:[],
  gameFinished:[],
  redrawTable:[],
  mySeat:[],
  sitOutPlayer:[],
  disconnectionTimer:[],
  cancelBuyin:[],
  popupRebuy:[],
  allStatus: [],
  isTournamentGame: false,
  stackAction: null
};

export default initialState;
